version: '3'
services:
  codnasq-db:
    image: raphsoft/codnasq:db-1.0
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
    - "5432"

  codnasq-web:
    image: raphsoft/codnasq:web-1.0
    depends_on: 
      - codnasq-db
    environment:
      DATABASE_HOST: codnasq-db
    ports:
    - "80:3000"