development:
  adapter: postgresql
  username: postgres
  password: postgres
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5
  database: codnasq_dev

production:
  adapter: postgresql
  username: postgres
  password: postgres
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5
  database: codnasq_dev

